{_commit: 9d08d0b, _src_path: /home/anekos/forge/template/copier/python-uv, package_name: voice_trigger,
  project_description: Trigger any command by your voice, project_name: voice-trigger,
  project_type: local}
